name: Build and Deploy api 

on: [push , pull_request ]

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: Pull Git Repo 
              uses: actions/checkout@v2

            - name: Setup Python Version 3.9
              uses: actions/setup-python@v2
              with:
                python-version: '3.9'
            - name: Upgrade Pip 
              run: python -m pip install --upgrade pip 
            - name: Install dependencies 
              run: pip install -r requirements.txt
